import type { Recipe } from '@/types/recipe';

// 内置中文家常菜谱库（curated，0 token、可控、可滚动扩充）。
// 字段：id / 菜名 / 菜系 / 难度(1-3) / 总耗时 / 人份 / 标签 / 食材(名称+用量+采购分类) / 有序步骤(动作+说明+火候+时长) / 贴士。
// 步骤顺序即"炒菜顺序"，前端分步模拟直接复用 steps 数组。

export const RECIPES: Recipe[] = [
  // ———————————— 家常 · 快手 ————————————
  {
    id: 'tomato-egg',
    name: '番茄炒蛋',
    cuisine: '家常',
    difficulty: 1,
    total_minutes: 12,
    servings: 2,
    tags: ['蛋', '不辣', '快手', '下饭'],
    ingredients: [
      { name: '鸡蛋', amount: '3个', category: '荤' },
      { name: '番茄', amount: '2个', category: '素' },
      { name: '小葱', amount: '1根', category: '素' },
      { name: '盐', amount: '2克', category: '调料' },
      { name: '白糖', amount: '1小勺', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '打蛋', detail: '鸡蛋加少许盐打散备用', duration: '1分钟' },
      { step: 2, action: '切番茄', detail: '番茄去蒂切块', duration: '2分钟' },
      { step: 3, action: '炒蛋', detail: '热油下蛋液，炒至刚凝固盛出', heat: '中火', duration: '1分钟' },
      { step: 4, action: '炒番茄', detail: '余油下番茄炒出红汁，加白糖提鲜', heat: '中火', duration: '2分钟' },
      { step: 5, action: '合炒', detail: '倒回鸡蛋翻匀，撒葱花出锅', heat: '大火', duration: '1分钟' },
    ],
    tips: '番茄炒出汁再回锅蛋，更入味；糖能中和酸味，不宜省。',
  },
  {
    id: 'potato-pepper',
    name: '青椒土豆丝',
    cuisine: '家常',
    difficulty: 1,
    total_minutes: 15,
    servings: 2,
    tags: ['素', '不辣', '快手', '下饭'],
    ingredients: [
      { name: '土豆', amount: '2个', category: '素' },
      { name: '青椒', amount: '1个', category: '素' },
      { name: '蒜', amount: '2瓣', category: '素' },
      { name: '白醋', amount: '1勺', category: '调料' },
      { name: '盐', amount: '2克', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '切丝泡水', detail: '土豆切细丝，清水泡去表面淀粉防粘', duration: '3分钟' },
      { step: 2, action: '备料', detail: '青椒切丝、蒜切末', duration: '2分钟' },
      { step: 3, action: '爆香', detail: '热油爆香蒜末', heat: '大火', duration: '30秒' },
      { step: 4, action: '快炒', detail: '下土豆丝大火快炒，沿锅边淋醋保持脆爽', heat: '大火', duration: '3分钟' },
      { step: 5, action: '调味', detail: '加青椒丝、盐翻炒断生出锅', heat: '大火', duration: '1分钟' },
    ],
    tips: '泡水+大火快炒是脆爽关键；醋分两次淋更香。',
  },
  {
    id: 'stir-broccoli',
    name: '清炒西兰花',
    cuisine: '家常',
    difficulty: 1,
    total_minutes: 12,
    servings: 2,
    tags: ['素', '不辣', '快手'],
    ingredients: [
      { name: '西兰花', amount: '1颗', category: '素' },
      { name: '蒜', amount: '3瓣', category: '素' },
      { name: '盐', amount: '2克', category: '调料' },
      { name: '蚝油', amount: '1勺', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '焯水', detail: '西兰花掰小朵，加盐沸水焯1分钟过凉', duration: '2分钟' },
      { step: 2, action: '爆香', detail: '热油爆香蒜末', heat: '中火', duration: '30秒' },
      { step: 3, action: '翻炒', detail: '下西兰花大火翻炒，加蚝油盐调味', heat: '大火', duration: '2分钟' },
    ],
    tips: '先焯后炒颜色更翠绿，且熟得均匀。',
  },
  {
    id: 'water-spinach',
    name: '蒜蓉空心菜',
    cuisine: '家常',
    difficulty: 1,
    total_minutes: 10,
    servings: 2,
    tags: ['素', '不辣', '快手'],
    ingredients: [
      { name: '空心菜', amount: '1把', category: '素' },
      { name: '蒜', amount: '4瓣', category: '素' },
      { name: '盐', amount: '2克', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '备料', detail: '空心菜切段、蒜剁蓉', duration: '2分钟' },
      { step: 2, action: '爆香', detail: '热油下一半蒜蓉爆香', heat: '大火', duration: '30秒' },
      { step: 3, action: '快炒', detail: '下菜大火快炒至塌软，加盐与余蒜翻匀', heat: '大火', duration: '2分钟' },
    ],
    tips: '空心菜极出水，必须大火快炒，否则出水变蔫。',
  },
  {
    id: 'hand-torn-cabbage',
    name: '手撕包菜',
    cuisine: '家常',
    difficulty: 1,
    total_minutes: 13,
    servings: 2,
    tags: ['素', '不辣', '快手', '下饭'],
    ingredients: [
      { name: '包菜', amount: '半颗', category: '素' },
      { name: '蒜', amount: '2瓣', category: '素' },
      { name: '干辣椒', amount: '2个', category: '调料' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '盐', amount: '2克', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '撕菜', detail: '包菜用手撕成大片，去掉硬梗', duration: '3分钟' },
      { step: 2, action: '爆香', detail: '热油下蒜末、干辣椒段爆香', heat: '中火', duration: '30秒' },
      { step: 3, action: '翻炒', detail: '下包菜大火翻炒至边缘焦边，加生抽盐', heat: '大火', duration: '3分钟' },
    ],
    tips: '手撕比刀切更入味；想要不辣可去干辣椒。',
  },
  {
    id: 'smashed-cucumber',
    name: '凉拌黄瓜',
    cuisine: '凉菜',
    difficulty: 1,
    total_minutes: 8,
    servings: 2,
    tags: ['素', '不辣', '快手', '凉菜'],
    ingredients: [
      { name: '黄瓜', amount: '2根', category: '素' },
      { name: '蒜', amount: '3瓣', category: '素' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '香醋', amount: '1勺', category: '调料' },
      { name: '香油', amount: '几滴', category: '调料' },
      { name: '盐', amount: '1克', category: '调料' },
    ],
    steps: [
      { step: 1, action: '拍黄瓜', detail: '黄瓜拍裂切段，加盐腌5分钟倒掉水', duration: '5分钟' },
      { step: 2, action: '调汁', detail: '蒜蓉+生抽+醋+香油调成料汁', duration: '2分钟' },
      { step: 3, action: '拌匀', detail: '料汁淋上拌匀即可', duration: '1分钟' },
    ],
    tips: '拍裂比切更挂汁；腌出水后倒掉更脆。',
  },
  {
    id: 'egg-fried-rice',
    name: '蛋炒饭',
    cuisine: '主食',
    difficulty: 1,
    total_minutes: 12,
    servings: 1,
    tags: ['蛋', '不辣', '快手'],
    ingredients: [
      { name: '隔夜米饭', amount: '1碗', category: '素' },
      { name: '鸡蛋', amount: '2个', category: '荤' },
      { name: '葱', amount: '1根', category: '素' },
      { name: '盐', amount: '2克', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '打蛋', detail: '鸡蛋打散，米饭搓散无结块', duration: '2分钟' },
      { step: 2, action: '炒蛋', detail: '热油倒蛋液，半凝固时下米饭同炒', heat: '中火', duration: '2分钟' },
      { step: 3, action: '翻炒', detail: '大火把饭炒散炒香，加盐葱花出锅', heat: '大火', duration: '3分钟' },
    ],
    tips: '隔夜饭水分少不粘；蛋液裹饭粒更金黄。',
  },
  {
    id: 'scallion-noodle',
    name: '葱油拌面',
    cuisine: '主食',
    difficulty: 1,
    total_minutes: 15,
    servings: 1,
    tags: ['素', '不辣', '快手'],
    ingredients: [
      { name: '面条', amount: '1人份', category: '素' },
      { name: '小葱', amount: '1把', category: '素' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '老抽', amount: '半勺', category: '调料' },
      { name: '糖', amount: '1小勺', category: '调料' },
      { name: '食用油', amount: '3勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '熬葱油', detail: '小葱切段，冷油小火熬至焦黄捞出', heat: '小火', duration: '6分钟' },
      { step: 2, action: '调汁', detail: '葱油中加生抽老抽糖煮匀成酱汁', heat: '小火', duration: '1分钟' },
      { step: 3, action: '煮面拌', detail: '面条煮熟过凉，拌入葱油酱汁', duration: '4分钟' },
    ],
    tips: '葱油小火慢熬才香；熬过的葱可留几根点缀。',
  },
  {
    id: 'plain-noodle',
    name: '阳春面',
    cuisine: '主食',
    difficulty: 1,
    total_minutes: 10,
    servings: 1,
    tags: ['素', '不辣', '快手'],
    ingredients: [
      { name: '细面', amount: '1人份', category: '素' },
      { name: '小葱', amount: '1根', category: '素' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '猪油', amount: '1勺', category: '调料' },
      { name: '盐', amount: '1克', category: '调料' },
    ],
    steps: [
      { step: 1, action: '备碗', detail: '碗里放生抽、猪油、盐、葱花', duration: '1分钟' },
      { step: 2, action: '煮面', detail: '面条煮熟，舀热汤冲开碗底料', duration: '4分钟' },
      { step: 3, action: '捞面', detail: '面捞入汤碗即可', duration: '1分钟' },
    ],
    tips: '猪油和热汤冲碗是汤头灵魂；没有猪油可用香油替代。',
  },

  // ———————————— 川菜 · 辣 ————————————
  {
    id: 'mapo-tofu',
    name: '麻婆豆腐',
    cuisine: '川菜',
    difficulty: 2,
    total_minutes: 20,
    servings: 2,
    tags: ['肉', '豆制品', '辣', '下饭'],
    ingredients: [
      { name: '嫩豆腐', amount: '1盒', category: '素' },
      { name: '肉末', amount: '100克', category: '荤' },
      { name: '郫县豆瓣酱', amount: '1勺', category: '调料' },
      { name: '花椒', amount: '1小勺', category: '调料' },
      { name: '蒜苗', amount: '2根', category: '素' },
      { name: '淀粉', amount: '1勺', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '焯豆腐', detail: '豆腐切块淡盐水焯1分钟去豆腥', duration: '2分钟' },
      { step: 2, action: '炒肉末', detail: '热油下肉末炒散至变色', heat: '中火', duration: '2分钟' },
      { step: 3, action: '炒红油', detail: '下豆瓣酱、花椒小火炒出红油', heat: '小火', duration: '2分钟' },
      { step: 4, action: '烧制', detail: '加水放豆腐轻推煮3分钟入味', heat: '中火', duration: '3分钟' },
      { step: 5, action: '勾芡', detail: '淋水淀粉收汁，撒蒜苗花椒面出锅', heat: '大火', duration: '1分钟' },
    ],
    tips: '豆腐用嫩豆腐、轻推不翻勺防碎；花椒现焙现碾更麻。',
  },
  {
    id: 'kungpao',
    name: '宫保鸡丁',
    cuisine: '川菜',
    difficulty: 2,
    total_minutes: 22,
    servings: 2,
    tags: ['肉', '辣', '下饭'],
    ingredients: [
      { name: '鸡胸肉', amount: '250克', category: '荤' },
      { name: '花生', amount: '1把', category: '素' },
      { name: '干辣椒', amount: '8个', category: '调料' },
      { name: '葱白', amount: '1段', category: '素' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '醋', amount: '1勺', category: '调料' },
      { name: '糖', amount: '1小勺', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '腌鸡丁', detail: '鸡丁加生抽、淀粉抓匀腌10分钟', duration: '10分钟' },
      { step: 2, action: '调汁', detail: '生抽+醋+糖+淀粉+水调成碗汁', duration: '2分钟' },
      { step: 3, action: '爆炒', detail: '热油下干辣椒、鸡丁大火滑炒变色', heat: '大火', duration: '2分钟' },
      { step: 4, action: '合炒', detail: '下葱白、花生，淋碗汁快速翻匀收汁', heat: '大火', duration: '2分钟' },
    ],
    tips: '鸡肉先滑后炒更嫩；花生最后放保持脆。',
  },
  {
    id: 'yuxiang',
    name: '鱼香肉丝',
    cuisine: '川菜',
    difficulty: 2,
    total_minutes: 22,
    servings: 2,
    tags: ['肉', '辣', '下饭'],
    ingredients: [
      { name: '里脊肉', amount: '250克', category: '荤' },
      { name: '木耳', amount: '1把', category: '素' },
      { name: '胡萝卜', amount: '半根', category: '素' },
      { name: '郫县豆瓣酱', amount: '1勺', category: '调料' },
      { name: '醋', amount: '1勺', category: '调料' },
      { name: '糖', amount: '1小勺', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '备料', detail: '肉切丝腌10分钟；木耳胡萝卜切丝', duration: '12分钟' },
      { step: 2, action: '调汁', detail: '醋+糖+生抽+淀粉调鱼香汁', duration: '2分钟' },
      { step: 3, action: '滑炒', detail: '热油下肉丝大火滑散盛出', heat: '大火', duration: '2分钟' },
      { step: 4, action: '合炒', detail: '下豆瓣酱炒红油，放配菜炒软，回肉丝淋汁翻匀', heat: '大火', duration: '3分钟' },
    ],
    tips: '鱼香味靠"糖醋+豆瓣"平衡，无鱼却有鱼香。',
  },
  {
    id: 'huiguorou',
    name: '回锅肉',
    cuisine: '川菜',
    difficulty: 2,
    total_minutes: 25,
    servings: 2,
    tags: ['肉', '辣', '下饭'],
    ingredients: [
      { name: '五花肉', amount: '300克', category: '荤' },
      { name: '青蒜', amount: '2根', category: '素' },
      { name: '郫县豆瓣酱', amount: '1勺', category: '调料' },
      { name: '甜面酱', amount: '半勺', category: '调料' },
      { name: '食用油', amount: '1勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '煮肉', detail: '五花肉整块冷水煮到筷子能扎透', duration: '15分钟' },
      { step: 2, action: '切片', detail: '肉晾凉切薄片；青蒜斜切', duration: '3分钟' },
      { step: 3, action: '煸炒', detail: '不放油下肉片煸出油至卷曲', heat: '中火', duration: '3分钟' },
      { step: 4, action: '调味', detail: '下豆瓣酱甜面酱炒香，放青蒜炒断生', heat: '大火', duration: '2分钟' },
    ],
    tips: '先煮后煸，肥而不腻；豆瓣酱炒出红油才香。',
  },
  {
    id: 'laziji',
    name: '辣子鸡',
    cuisine: '川菜',
    difficulty: 3,
    total_minutes: 35,
    servings: 2,
    tags: ['肉', '辣', '下饭'],
    ingredients: [
      { name: '鸡腿', amount: '2个', category: '荤' },
      { name: '干辣椒', amount: '1把', category: '调料' },
      { name: '花椒', amount: '1小勺', category: '调料' },
      { name: '料酒', amount: '1勺', category: '调料' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '食用油', amount: '适量(炸)', category: '调料' },
    ],
    steps: [
      { step: 1, action: '腌鸡', detail: '鸡腿切小块，料酒生抽腌15分钟', duration: '15分钟' },
      { step: 2, action: '炸鸡', detail: '油温六成热炸至金黄外脆', heat: '中火', duration: '6分钟' },
      { step: 3, action: '爆香', detail: '底油下干辣椒花椒小火煸香', heat: '小火', duration: '2分钟' },
      { step: 4, action: '合炒', detail: '下鸡块大火翻炒裹满辣香出锅', heat: '大火', duration: '2分钟' },
    ],
    tips: '辣椒多到看不见鸡才正宗；花椒小火别糊。',
  },
  {
    id: 'boiled-pork',
    name: '水煮肉片',
    cuisine: '川菜',
    difficulty: 3,
    total_minutes: 35,
    servings: 2,
    tags: ['肉', '辣', '下饭'],
    ingredients: [
      { name: '里脊肉', amount: '300克', category: '荤' },
      { name: '黄豆芽', amount: '1把', category: '素' },
      { name: '莴笋', amount: '半根', category: '素' },
      { name: '郫县豆瓣酱', amount: '2勺', category: '调料' },
      { name: '干辣椒', amount: '适量', category: '调料' },
      { name: '花椒', amount: '1小勺', category: '调料' },
      { name: '食用油', amount: '3勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '腌肉', detail: '肉切片加生抽淀粉腌10分钟', duration: '10分钟' },
      { step: 2, action: '炒底菜', detail: '豆芽莴笋焯熟铺碗底', duration: '3分钟' },
      { step: 3, action: '炒红汤', detail: '豆瓣酱炒红油，加水煮开下肉片滑熟', heat: '中火', duration: '5分钟' },
      { step: 4, action: '泼油', detail: '连汤倒碗，撒辣椒花椒，热油激香', heat: '大火', duration: '2分钟' },
    ],
    tips: '肉片涮熟即捞，久煮变老；最后泼油是灵魂。',
  },

  // ———————————— 家常 · 不辣荤 ————————————
  {
    id: 'cola-wings',
    name: '可乐鸡翅',
    cuisine: '家常',
    difficulty: 1,
    total_minutes: 25,
    servings: 2,
    tags: ['肉', '甜', '不辣', '快手'],
    ingredients: [
      { name: '鸡翅中', amount: '8个', category: '荤' },
      { name: '可乐', amount: '1罐', category: '调料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '姜', amount: '2片', category: '素' },
      { name: '食用油', amount: '1勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '焯水', detail: '鸡翅两面划口，冷水焯去血沫', duration: '4分钟' },
      { step: 2, action: '煎翅', detail: '少油把鸡翅煎至两面金黄', heat: '中火', duration: '4分钟' },
      { step: 3, action: '烧制', detail: '加生抽、可乐没过鸡翅，盖盖小火焖', heat: '小火', duration: '12分钟' },
      { step: 4, action: '收汁', detail: '大火收汁裹亮出锅', heat: '大火', duration: '3分钟' },
    ],
    tips: '可乐本身带甜，一般不需再加糖；收汁要勤翻防糊。',
  },
  {
    id: 'braised-pork',
    name: '红烧肉',
    cuisine: '家常',
    difficulty: 3,
    total_minutes: 60,
    servings: 3,
    tags: ['肉', '不辣', '下饭'],
    ingredients: [
      { name: '五花肉', amount: '500克', category: '荤' },
      { name: '冰糖', amount: '20克', category: '调料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
      { name: '姜', amount: '3片', category: '素' },
      { name: '料酒', amount: '1勺', category: '调料' },
      { name: '食用油', amount: '1勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '焯水', detail: '五花肉切块冷水焯去血沫', duration: '5分钟' },
      { step: 2, action: '炒糖色', detail: '冰糖小火炒至枣红冒泡', heat: '小火', duration: '3分钟' },
      { step: 3, action: '上色', detail: '下肉块翻炒裹糖色，烹料酒生抽老抽', heat: '中火', duration: '3分钟' },
      { step: 4, action: '炖煮', detail: '加热水没过肉，小火慢炖40分钟', heat: '小火', duration: '40分钟' },
      { step: 5, action: '收汁', detail: '大火收浓汤汁裹肉', heat: '大火', duration: '5分钟' },
    ],
    tips: '炒糖色全程小火，糖一焦就苦；加热水别加冷水否则肉发柴。',
  },
  {
    id: 'sweet-sour-pork',
    name: '糖醋里脊',
    cuisine: '家常',
    difficulty: 2,
    total_minutes: 30,
    servings: 2,
    tags: ['肉', '甜', '不辣'],
    ingredients: [
      { name: '里脊肉', amount: '300克', category: '荤' },
      { name: '番茄酱', amount: '2勺', category: '调料' },
      { name: '白醋', amount: '1勺', category: '调料' },
      { name: '糖', amount: '2勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '食用油', amount: '适量(炸)', category: '调料' },
    ],
    steps: [
      { step: 1, action: '腌切', detail: '里脊切条，加盐料酒腌10分钟裹淀粉', duration: '12分钟' },
      { step: 2, action: '炸制', detail: '油温六成炸定型，复炸至金黄脆', heat: '中火', duration: '6分钟' },
      { step: 3, action: '调汁', detail: '番茄酱+糖+醋+水小火煮稠', heat: '小火', duration: '2分钟' },
      { step: 4, action: '挂汁', detail: '倒肉条快速翻匀裹汁出锅', heat: '大火', duration: '1分钟' },
    ],
    tips: '复炸一次才外脆里嫩；糖醋汁现调现裹防回软。',
  },
  {
    id: 'sweet-sour-rib',
    name: '糖醋排骨',
    cuisine: '苏菜',
    difficulty: 2,
    total_minutes: 40,
    servings: 2,
    tags: ['肉', '甜', '不辣', '下饭'],
    ingredients: [
      { name: '小排', amount: '500克', category: '荤' },
      { name: '冰糖', amount: '30克', category: '调料' },
      { name: '香醋', amount: '2勺', category: '调料' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '姜', amount: '2片', category: '素' },
      { name: '食用油', amount: '1勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '焯水', detail: '排骨冷水焯去血沫', duration: '5分钟' },
      { step: 2, action: '炒糖色', detail: '冰糖小火炒枣红，下排骨裹色', heat: '小火', duration: '3分钟' },
      { step: 3, action: '焖煮', detail: '加醋生抽姜与热水，小火焖30分钟', heat: '小火', duration: '30分钟' },
      { step: 4, action: '收汁', detail: '大火收汁裹亮出锅', heat: '大火', duration: '4分钟' },
    ],
    tips: '糖和醋比例约 1:1；出锅前可补一勺醋更亮酸。',
  },
  {
    id: 'muxu-pork',
    name: '木须肉',
    cuisine: '鲁菜',
    difficulty: 2,
    total_minutes: 22,
    servings: 2,
    tags: ['肉', '蛋', '不辣', '下饭'],
    ingredients: [
      { name: '里脊肉', amount: '200克', category: '荤' },
      { name: '鸡蛋', amount: '2个', category: '荤' },
      { name: '木耳', amount: '1把', category: '素' },
      { name: '黄瓜', amount: '半根', category: '素' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '备料', detail: '肉片腌10分钟；木耳泡发；黄瓜切片；鸡蛋炒碎', duration: '12分钟' },
      { step: 2, action: '滑肉', detail: '热油下肉片滑散盛出', heat: '大火', duration: '2分钟' },
      { step: 3, action: '合炒', detail: '下木耳黄瓜翻炒，回肉片鸡蛋，生抽调味', heat: '大火', duration: '3分钟' },
    ],
    tips: '鸡蛋先炒盛出再合炒，口感更嫩不老。',
  },

  // ———————————— 粤菜 · 海鲜不辣 ————————————
  {
    id: 'steamed-bass',
    name: '清蒸鲈鱼',
    cuisine: '粤菜',
    difficulty: 2,
    total_minutes: 20,
    servings: 2,
    tags: ['海鲜', '不辣'],
    ingredients: [
      { name: '鲈鱼', amount: '1条', category: '荤' },
      { name: '姜', amount: '1块', category: '素' },
      { name: '葱', amount: '2根', category: '素' },
      { name: '蒸鱼豉油', amount: '2勺', category: '调料' },
      { name: '料酒', amount: '1勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '处理', detail: '鱼洗净两面划刀，抹料酒铺姜丝', duration: '5分钟' },
      { step: 2, action: '蒸制', detail: '水开上锅大火蒸8分钟，倒掉腥水', heat: '大火', duration: '8分钟' },
      { step: 3, action: '泼油', detail: '铺葱丝，淋蒸鱼豉油，热油激香', heat: '大火', duration: '2分钟' },
    ],
    tips: '蒸的时间看鱼大小，过久肉老；蒸鱼豉油最后淋。',
  },
  {
    id: 'poached-shrimp',
    name: '白灼虾',
    cuisine: '粤菜',
    difficulty: 1,
    total_minutes: 12,
    servings: 2,
    tags: ['海鲜', '不辣', '快手'],
    ingredients: [
      { name: '基围虾', amount: '300克', category: '荤' },
      { name: '姜', amount: '3片', category: '素' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '香油', amount: '几滴', category: '调料' },
    ],
    steps: [
      { step: 1, action: '备水', detail: '水加姜片烧开', duration: '3分钟' },
      { step: 2, action: '灼虾', detail: '虾入锅煮到变红卷曲捞出', heat: '大火', duration: '3分钟' },
      { step: 3, action: '蘸料', detail: '生抽加姜末香油调蘸汁', duration: '1分钟' },
    ],
    tips: '虾一红就捞，久煮肉柴；配姜醋汁去腥。',
  },
  {
    id: 'scallop-vermicelli',
    name: '蒜蓉粉丝蒸扇贝',
    cuisine: '粤菜',
    difficulty: 2,
    total_minutes: 20,
    servings: 2,
    tags: ['海鲜', '不辣'],
    ingredients: [
      { name: '扇贝', amount: '6个', category: '荤' },
      { name: '粉丝', amount: '1把', category: '素' },
      { name: '蒜', amount: '1头', category: '素' },
      { name: '蒸鱼豉油', amount: '2勺', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '备料', detail: '粉丝泡软铺贝上；蒜剁蓉', duration: '8分钟' },
      { step: 2, action: '炒蒜蓉', detail: '蒜蓉一半炸金黄，与生蒜混合铺贝', heat: '小火', duration: '3分钟' },
      { step: 3, action: '蒸制', detail: '水开蒸5分钟，淋豉油', heat: '大火', duration: '5分钟' },
    ],
    tips: '金银蒜（生熟各半）更香；蒸久扇贝老。',
  },

  // ———————————— 湘菜 · 辣 ————————————
  {
    id: 'duojiao-fishhead',
    name: '剁椒鱼头',
    cuisine: '湘菜',
    difficulty: 3,
    total_minutes: 30,
    servings: 3,
    tags: ['海鲜', '辣', '下饭'],
    ingredients: [
      { name: '胖鱼头', amount: '1个', category: '荤' },
      { name: '剁椒', amount: '3勺', category: '调料' },
      { name: '姜蒜', amount: '适量', category: '素' },
      { name: '蒸鱼豉油', amount: '2勺', category: '调料' },
      { name: '葱', amount: '1根', category: '素' },
    ],
    steps: [
      { step: 1, action: '处理', detail: '鱼头劈开腌料酒，铺姜蒜', duration: '8分钟' },
      { step: 2, action: '铺剁椒', detail: '剁椒铺满鱼头，淋豉油', duration: '2分钟' },
      { step: 3, action: '蒸制', detail: '水开大火蒸12分钟', heat: '大火', duration: '12分钟' },
      { step: 4, action: '泼油', detail: '撒葱，热油激香', heat: '大火', duration: '2分钟' },
    ],
    tips: '鱼头选胖头鱼；蒸足时间才熟透入味。',
  },
  {
    id: 'farm-pork',
    name: '农家小炒肉',
    cuisine: '湘菜',
    difficulty: 2,
    total_minutes: 20,
    servings: 2,
    tags: ['肉', '辣', '下饭'],
    ingredients: [
      { name: '五花肉', amount: '250克', category: '荤' },
      { name: '青红椒', amount: '各2个', category: '素' },
      { name: '蒜', amount: '3瓣', category: '素' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '豆豉', amount: '1勺', category: '调料' },
      { name: '食用油', amount: '1勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '备料', detail: '五花肉去皮切薄片；椒切滚刀', duration: '5分钟' },
      { step: 2, action: '煸肉', detail: '不放油下肉片煸出油至焦边', heat: '中火', duration: '4分钟' },
      { step: 3, action: '合炒', detail: '下蒜豆豉炒香，放青红椒炒断生生抽调味', heat: '大火', duration: '3分钟' },
    ],
    tips: '带皮会更弹，去皮更香；椒要炒到虎皮更入味。',
  },
  {
    id: 'beef-stirfry',
    name: '小炒黄牛肉',
    cuisine: '湘菜',
    difficulty: 2,
    total_minutes: 18,
    servings: 2,
    tags: ['肉', '辣', '下饭'],
    ingredients: [
      { name: '黄牛肉', amount: '250克', category: '荤' },
      { name: '小米辣', amount: '4个', category: '调料' },
      { name: '香菜', amount: '1把', category: '素' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '腌牛肉', detail: '牛肉逆纹切薄片，生抽淀粉腌10分钟', duration: '10分钟' },
      { step: 2, action: '爆炒', detail: '热油大火下牛肉滑散变色即盛', heat: '大火', duration: '1分钟' },
      { step: 3, action: '合炒', detail: '下小米辣爆香，回牛肉，放香菜段快炒', heat: '大火', duration: '2分钟' },
    ],
    tips: '牛肉逆纹切、大火快炒才嫩；香菜后放保香。',
  },

  // ———————————— 素菜 ————————————
  {
    id: 'di-san-xian',
    name: '地三鲜',
    cuisine: '家常',
    difficulty: 2,
    total_minutes: 25,
    servings: 2,
    tags: ['素', '不辣', '下饭'],
    ingredients: [
      { name: '土豆', amount: '1个', category: '素' },
      { name: '茄子', amount: '1根', category: '素' },
      { name: '青椒', amount: '1个', category: '素' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '糖', amount: '半勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '食用油', amount: '适量(炸)', category: '调料' },
    ],
    steps: [
      { step: 1, action: '炸制', detail: '土豆茄子分别炸至金黄', heat: '中火', duration: '6分钟' },
      { step: 2, action: '调汁', detail: '生抽+糖+淀粉+水调碗汁', duration: '2分钟' },
      { step: 3, action: '合炒', detail: '底油下青椒，回三鲜淋汁翻匀', heat: '大火', duration: '3分钟' },
    ],
    tips: '茄子先炸吸油少；碗汁提前调好防手忙。',
  },
  {
    id: 'dry-beans',
    name: '干煸四季豆',
    cuisine: '家常',
    difficulty: 2,
    total_minutes: 18,
    servings: 2,
    tags: ['素', '不辣', '下饭'],
    ingredients: [
      { name: '四季豆', amount: '300克', category: '素' },
      { name: '芽菜', amount: '1勺', category: '素' },
      { name: '蒜', amount: '2瓣', category: '素' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '食用油', amount: '2勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '煸豆', detail: '四季豆撕筋，少油煸到起皱表皮焦', heat: '中火', duration: '8分钟' },
      { step: 2, action: '爆香', detail: '下蒜末芽菜炒香', heat: '中火', duration: '2分钟' },
      { step: 3, action: '调味', detail: '回四季豆生抽翻炒出锅', heat: '大火', duration: '2分钟' },
    ],
    tips: '四季豆必须煸熟透，生豆有毒；想要香辣可加肉末辣椒。',
  },

  // ———————————— 汤羹 ————————————
  {
    id: 'seaweed-egg-soup',
    name: '紫菜蛋花汤',
    cuisine: '汤羹',
    difficulty: 1,
    total_minutes: 8,
    servings: 2,
    tags: ['蛋', '不辣', '快手', '汤'],
    ingredients: [
      { name: '紫菜', amount: '1小把', category: '素' },
      { name: '鸡蛋', amount: '1个', category: '荤' },
      { name: '葱', amount: '1根', category: '素' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '香油', amount: '几滴', category: '调料' },
      { name: '盐', amount: '1克', category: '调料' },
    ],
    steps: [
      { step: 1, action: '烧水', detail: '水开下紫菜煮1分钟', duration: '2分钟' },
      { step: 2, action: '淋蛋', detail: '转小火，蛋液画圈淋入成蛋花', heat: '小火', duration: '1分钟' },
      { step: 3, action: '调味', detail: '加盐生抽香油葱花出锅', duration: '1分钟' },
    ],
    tips: '淋蛋液时火要小，蛋花才细；关火再淋香油。',
  },
  {
    id: 'tomato-beef-soup',
    name: '西红柿牛腩汤',
    cuisine: '汤羹',
    difficulty: 3,
    total_minutes: 75,
    servings: 3,
    tags: ['肉', '不辣', '汤'],
    ingredients: [
      { name: '牛腩', amount: '500克', category: '荤' },
      { name: '番茄', amount: '3个', category: '素' },
      { name: '姜', amount: '3片', category: '素' },
      { name: '盐', amount: '3克', category: '调料' },
      { name: '食用油', amount: '1勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '焯牛腩', detail: '牛腩切块冷水焯去血沫', duration: '6分钟' },
      { step: 2, action: '炒番茄', detail: '番茄切块炒出沙，加牛腩翻炒', heat: '中火', duration: '5分钟' },
      { step: 3, action: '炖煮', detail: '加热水小火炖60分钟至软', heat: '小火', duration: '60分钟' },
      { step: 4, action: '调味', detail: '加盐出锅', duration: '1分钟' },
    ],
    tips: '牛腩炖久才烂；番茄炒出沙汤更浓。',
  },
  {
    id: 'rib-corn-soup',
    name: '排骨玉米汤',
    cuisine: '汤羹',
    difficulty: 2,
    total_minutes: 60,
    servings: 3,
    tags: ['肉', '不辣', '汤'],
    ingredients: [
      { name: '排骨', amount: '500克', category: '荤' },
      { name: '玉米', amount: '2根', category: '素' },
      { name: '胡萝卜', amount: '1根', category: '素' },
      { name: '姜', amount: '3片', category: '素' },
      { name: '盐', amount: '3克', category: '调料' },
    ],
    steps: [
      { step: 1, action: '焯排骨', detail: '排骨冷水焯去血沫', duration: '5分钟' },
      { step: 2, action: '炖煮', detail: '排骨玉米胡萝卜姜加水小火炖50分钟', heat: '小火', duration: '50分钟' },
      { step: 3, action: '调味', detail: '加盐出锅', duration: '1分钟' },
    ],
    tips: '冷水下料汤清；玉米选水果玉米更甜。',
  },
  {
    id: 'wintermelon-ball-soup',
    name: '冬瓜丸子汤',
    cuisine: '汤羹',
    difficulty: 2,
    total_minutes: 25,
    servings: 2,
    tags: ['肉', '不辣', '汤'],
    ingredients: [
      { name: '猪肉馅', amount: '200克', category: '荤' },
      { name: '冬瓜', amount: '300克', category: '素' },
      { name: '姜', amount: '2片', category: '素' },
      { name: '盐', amount: '3克', category: '调料' },
      { name: '香油', amount: '几滴', category: '调料' },
    ],
    steps: [
      { step: 1, action: '调馅', detail: '肉馅加盐姜末香油搅上劲', duration: '5分钟' },
      { step: 2, action: '煮丸', detail: '水开下冬瓜，丸子挤入煮熟浮起', heat: '中火', duration: '8分钟' },
      { step: 3, action: '调味', detail: '加盐香油出锅', duration: '1分钟' },
    ],
    tips: '丸子冷水下易散，水微开挤入；冬瓜易熟别久煮。',
  },

  // ———————————— 浙菜 ————————————
  {
    id: 'xihu-vinegar-fish',
    name: '西湖醋鱼',
    cuisine: '浙菜',
    difficulty: 3,
    total_minutes: 30,
    servings: 2,
    tags: ['海鲜', '不辣', '下饭'],
    ingredients: [
      { name: '草鱼', amount: '1条', category: '荤' },
      { name: '姜', amount: '1块', category: '素' },
      { name: '镇江香醋', amount: '3勺', category: '调料' },
      { name: '糖', amount: '2勺', category: '调料' },
      { name: '酱油', amount: '1勺', category: '调料' },
      { name: '淀粉', amount: '1勺', category: '调料' },
    ],
    steps: [
      { step: 1, action: '煮鱼', detail: '鱼沸水汆熟捞出装盘', heat: '大火', duration: '8分钟' },
      { step: 2, action: '调汁', detail: '醋糖酱油水煮开勾芡成糖醋汁', heat: '中火', duration: '3分钟' },
      { step: 3, action: '浇汁', detail: '汁淋鱼身，撒姜末', duration: '1分钟' },
    ],
    tips: '鱼要活鱼现做；糖醋汁酸甜平衡是关键。',
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}
